/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/csrf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Issue the request verification token. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/captcha": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Issue a browser-bound login image challenge; refreshing invalidates the previous image. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfCaptchaView"];
                        "application/json": components["schemas"]["ApiResponseOfCaptchaView"];
                        "text/json": components["schemas"]["ApiResponseOfCaptchaView"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Establish an authenticated session. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginInput"];
                    "text/json": components["schemas"]["LoginInput"];
                    "application/*+json": components["schemas"]["LoginInput"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfUserView"];
                        "application/json": components["schemas"]["ApiResponseOfUserView"];
                        "text/json": components["schemas"]["ApiResponseOfUserView"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read the current account. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfUserView"];
                        "application/json": components["schemas"]["ApiResponseOfUserView"];
                        "text/json": components["schemas"]["ApiResponseOfUserView"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** End the current session. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfboolean"];
                        "application/json": components["schemas"]["ApiResponseOfboolean"];
                        "text/json": components["schemas"]["ApiResponseOfboolean"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change password and invalidate the current session. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PasswordInput"];
                    "text/json": components["schemas"]["PasswordInput"];
                    "application/*+json": components["schemas"]["PasswordInput"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfboolean"];
                        "application/json": components["schemas"]["ApiResponseOfboolean"];
                        "text/json": components["schemas"]["ApiResponseOfboolean"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/themes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read packaged themes and independent saved profiles. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfThemesView"];
                        "application/json": components["schemas"]["ApiResponseOfThemesView"];
                        "text/json": components["schemas"]["ApiResponseOfThemesView"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/themes/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Validate a non-persistent appearance preview. */
        get: {
            parameters: {
                query?: {
                    themeId?: string;
                    accentColor?: string;
                    heroTitle?: string;
                    heroDescription?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfThemeView"];
                        "application/json": components["schemas"]["ApiResponseOfThemeView"];
                        "text/json": components["schemas"]["ApiResponseOfThemeView"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/themes/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Atomically save and activate a packaged theme. */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ThemeApplyInput"];
                    "text/json": components["schemas"]["ThemeApplyInput"];
                    "application/*+json": components["schemas"]["ThemeApplyInput"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfThemesView"];
                        "application/json": components["schemas"]["ApiResponseOfThemesView"];
                        "text/json": components["schemas"]["ApiResponseOfThemesView"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dashboard counts. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfStatsView"];
                        "application/json": components["schemas"]["ApiResponseOfStatsView"];
                        "text/json": components["schemas"]["ApiResponseOfStatsView"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/contents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List content drafts. */
        get: {
            parameters: {
                query?: {
                    kind?: string;
                    q?: string;
                    page?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfPageResultOfContentView"];
                        "application/json": components["schemas"]["ApiResponseOfPageResultOfContentView"];
                        "text/json": components["schemas"]["ApiResponseOfPageResultOfContentView"];
                    };
                };
            };
        };
        put?: never;
        /** Create a draft. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ContentInput"];
                    "text/json": components["schemas"]["ContentInput"];
                    "application/*+json": components["schemas"]["ContentInput"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfContentView"];
                        "application/json": components["schemas"]["ApiResponseOfContentView"];
                        "text/json": components["schemas"]["ApiResponseOfContentView"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/contents/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get draft or authenticated preview data. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfContentView"];
                        "application/json": components["schemas"]["ApiResponseOfContentView"];
                        "text/json": components["schemas"]["ApiResponseOfContentView"];
                    };
                };
            };
        };
        /** Save an expected draft version. */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ContentInput"];
                    "text/json": components["schemas"]["ContentInput"];
                    "application/*+json": components["schemas"]["ContentInput"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfContentView"];
                        "application/json": components["schemas"]["ApiResponseOfContentView"];
                        "text/json": components["schemas"]["ApiResponseOfContentView"];
                    };
                };
            };
        };
        post?: never;
        /** Delete the expected version. */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["VersionInput"];
                    "text/json": components["schemas"]["VersionInput"];
                    "application/*+json": components["schemas"]["VersionInput"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfboolean"];
                        "application/json": components["schemas"]["ApiResponseOfboolean"];
                        "text/json": components["schemas"]["ApiResponseOfboolean"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/contents/{id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Publish the expected version. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["VersionInput"];
                    "text/json": components["schemas"]["VersionInput"];
                    "application/*+json": components["schemas"]["VersionInput"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfContentView"];
                        "application/json": components["schemas"]["ApiResponseOfContentView"];
                        "text/json": components["schemas"]["ApiResponseOfContentView"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/contents/{id}/unpublish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Withdraw public content. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["VersionInput"];
                    "text/json": components["schemas"]["VersionInput"];
                    "application/*+json": components["schemas"]["VersionInput"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfContentView"];
                        "application/json": components["schemas"]["ApiResponseOfContentView"];
                        "text/json": components["schemas"]["ApiResponseOfContentView"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/taxonomy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read taxonomy. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfListOfTaxonomy"];
                        "application/json": components["schemas"]["ApiResponseOfListOfTaxonomy"];
                        "text/json": components["schemas"]["ApiResponseOfListOfTaxonomy"];
                    };
                };
            };
        };
        put?: never;
        /** Create taxonomy. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TaxonomyInput"];
                    "text/json": components["schemas"]["TaxonomyInput"];
                    "application/*+json": components["schemas"]["TaxonomyInput"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfTaxonomy"];
                        "application/json": components["schemas"]["ApiResponseOfTaxonomy"];
                        "text/json": components["schemas"]["ApiResponseOfTaxonomy"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/taxonomy/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update taxonomy. */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TaxonomyInput"];
                    "text/json": components["schemas"]["TaxonomyInput"];
                    "application/*+json": components["schemas"]["TaxonomyInput"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfTaxonomy"];
                        "application/json": components["schemas"]["ApiResponseOfTaxonomy"];
                        "text/json": components["schemas"]["ApiResponseOfTaxonomy"];
                    };
                };
            };
        };
        post?: never;
        /** Delete unused taxonomy. */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfboolean"];
                        "application/json": components["schemas"]["ApiResponseOfboolean"];
                        "text/json": components["schemas"]["ApiResponseOfboolean"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read uploaded file metadata. */
        get: {
            parameters: {
                query?: {
                    page?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfPageResultOfAssetView"];
                        "application/json": components["schemas"]["ApiResponseOfPageResultOfAssetView"];
                        "text/json": components["schemas"]["ApiResponseOfPageResultOfAssetView"];
                    };
                };
            };
        };
        put?: never;
        /** Upload one verified file. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        file?: components["schemas"]["IFormFile"];
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfAssetView"];
                        "application/json": components["schemas"]["ApiResponseOfAssetView"];
                        "text/json": components["schemas"]["ApiResponseOfAssetView"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/assets/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete an unreferenced file. */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfboolean"];
                        "application/json": components["schemas"]["ApiResponseOfboolean"];
                        "text/json": components["schemas"]["ApiResponseOfboolean"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read moderated and pending comments. */
        get: {
            parameters: {
                query?: {
                    page?: number;
                    pending?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfPageResultOfComment"];
                        "application/json": components["schemas"]["ApiResponseOfPageResultOfComment"];
                        "text/json": components["schemas"]["ApiResponseOfPageResultOfComment"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/comments/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Approve or hide a comment. */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ModerateInput"];
                    "text/json": components["schemas"]["ModerateInput"];
                    "application/*+json": components["schemas"]["ModerateInput"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfComment"];
                        "application/json": components["schemas"]["ApiResponseOfComment"];
                        "text/json": components["schemas"]["ApiResponseOfComment"];
                    };
                };
            };
        };
        post?: never;
        /** Delete a comment. */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfboolean"];
                        "application/json": components["schemas"]["ApiResponseOfboolean"];
                        "text/json": components["schemas"]["ApiResponseOfboolean"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/menu": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read menu configuration. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfIReadOnlyListOfMenuView"];
                        "application/json": components["schemas"]["ApiResponseOfIReadOnlyListOfMenuView"];
                        "text/json": components["schemas"]["ApiResponseOfIReadOnlyListOfMenuView"];
                    };
                };
            };
        };
        put?: never;
        /** Create menu entry. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["MenuInput"];
                    "text/json": components["schemas"]["MenuInput"];
                    "application/*+json": components["schemas"]["MenuInput"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfMenuView"];
                        "application/json": components["schemas"]["ApiResponseOfMenuView"];
                        "text/json": components["schemas"]["ApiResponseOfMenuView"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/menu/targets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search published content and taxonomy for automatic menu destinations. */
        get: {
            parameters: {
                query?: {
                    type?: string;
                    q?: string;
                    page?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfPageResultOfMenuTarget"];
                        "application/json": components["schemas"]["ApiResponseOfPageResultOfMenuTarget"];
                        "text/json": components["schemas"]["ApiResponseOfPageResultOfMenuTarget"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/menu/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update menu entry. */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["MenuInput"];
                    "text/json": components["schemas"]["MenuInput"];
                    "application/*+json": components["schemas"]["MenuInput"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfMenuView"];
                        "application/json": components["schemas"]["ApiResponseOfMenuView"];
                        "text/json": components["schemas"]["ApiResponseOfMenuView"];
                    };
                };
            };
        };
        post?: never;
        /** Delete menu entry. */
        delete: {
            parameters: {
                query?: {
                    version?: number;
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfboolean"];
                        "application/json": components["schemas"]["ApiResponseOfboolean"];
                        "text/json": components["schemas"]["ApiResponseOfboolean"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read site settings. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfSiteSettings"];
                        "application/json": components["schemas"]["ApiResponseOfSiteSettings"];
                        "text/json": components["schemas"]["ApiResponseOfSiteSettings"];
                    };
                };
            };
        };
        /** Update site settings. */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SettingsInput"];
                    "text/json": components["schemas"]["SettingsInput"];
                    "application/*+json": components["schemas"]["SettingsInput"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfSiteSettings"];
                        "application/json": components["schemas"]["ApiResponseOfSiteSettings"];
                        "text/json": components["schemas"]["ApiResponseOfSiteSettings"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List safe account records. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfIReadOnlyListOfUserView"];
                        "application/json": components["schemas"]["ApiResponseOfIReadOnlyListOfUserView"];
                        "text/json": components["schemas"]["ApiResponseOfIReadOnlyListOfUserView"];
                    };
                };
            };
        };
        put?: never;
        /** Create an account. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UserInput"];
                    "text/json": components["schemas"]["UserInput"];
                    "application/*+json": components["schemas"]["UserInput"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfUserView"];
                        "application/json": components["schemas"]["ApiResponseOfUserView"];
                        "text/json": components["schemas"]["ApiResponseOfUserView"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update account and revoke existing sessions. */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UserInput"];
                    "text/json": components["schemas"]["UserInput"];
                    "application/*+json": components["schemas"]["UserInput"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfUserView"];
                        "application/json": components["schemas"]["ApiResponseOfUserView"];
                        "text/json": components["schemas"]["ApiResponseOfUserView"];
                    };
                };
            };
        };
        post?: never;
        /** Delete account. */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfboolean"];
                        "application/json": components["schemas"]["ApiResponseOfboolean"];
                        "text/json": components["schemas"]["ApiResponseOfboolean"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Page administrative audit events. */
        get: {
            parameters: {
                query?: {
                    page?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfPageResultOfAuditEntry"];
                        "application/json": components["schemas"]["ApiResponseOfPageResultOfAuditEntry"];
                        "text/json": components["schemas"]["ApiResponseOfPageResultOfAuditEntry"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/theme": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read only the current effective appearance. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfThemeView"];
                        "application/json": components["schemas"]["ApiResponseOfThemeView"];
                        "text/json": components["schemas"]["ApiResponseOfThemeView"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/contents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List public content. */
        get: {
            parameters: {
                query?: {
                    kind?: string;
                    q?: string;
                    categoryId?: string;
                    tagId?: string;
                    page?: number;
                    pageSize?: number;
                    search?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfPageResultOfContentView"];
                        "application/json": components["schemas"]["ApiResponseOfPageResultOfContentView"];
                        "text/json": components["schemas"]["ApiResponseOfPageResultOfContentView"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/contents/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read one published snapshot. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfContentView"];
                        "application/json": components["schemas"]["ApiResponseOfContentView"];
                        "text/json": components["schemas"]["ApiResponseOfContentView"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read site metadata. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfSiteSettings"];
                        "application/json": components["schemas"]["ApiResponseOfSiteSettings"];
                        "text/json": components["schemas"]["ApiResponseOfSiteSettings"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/taxonomy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read public taxonomy. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfListOfTaxonomy"];
                        "application/json": components["schemas"]["ApiResponseOfListOfTaxonomy"];
                        "text/json": components["schemas"]["ApiResponseOfListOfTaxonomy"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/menu": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read public navigation. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfIReadOnlyListOfMenuView"];
                        "application/json": components["schemas"]["ApiResponseOfIReadOnlyListOfMenuView"];
                        "text/json": components["schemas"]["ApiResponseOfIReadOnlyListOfMenuView"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/sitemap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all published sitemap records. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfIReadOnlyListOfContentView"];
                        "application/json": components["schemas"]["ApiResponseOfIReadOnlyListOfContentView"];
                        "text/json": components["schemas"]["ApiResponseOfIReadOnlyListOfContentView"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read approved comments. */
        get: {
            parameters: {
                query?: {
                    contentId?: string;
                    page?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfPageResultOfComment"];
                        "application/json": components["schemas"]["ApiResponseOfPageResultOfComment"];
                        "text/json": components["schemas"]["ApiResponseOfPageResultOfComment"];
                    };
                };
            };
        };
        put?: never;
        /** Queue a comment for review. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CommentInput"];
                    "text/json": components["schemas"]["CommentInput"];
                    "application/*+json": components["schemas"]["CommentInput"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfComment"];
                        "application/json": components["schemas"]["ApiResponseOfComment"];
                        "text/json": components["schemas"]["ApiResponseOfComment"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Consistent HTTP response envelope. */
        ApiResponseOfAssetView: {
            code: string;
            message: string;
            data: null | components["schemas"]["AssetView"];
            traceId: string;
        };
        /** @description Consistent HTTP response envelope. */
        ApiResponseOfboolean: {
            code: string;
            message: string;
            data: boolean;
            traceId: string;
        };
        /** @description Consistent HTTP response envelope. */
        ApiResponseOfCaptchaView: {
            code: string;
            message: string;
            data: null | components["schemas"]["CaptchaView"];
            traceId: string;
        };
        /** @description Consistent HTTP response envelope. */
        ApiResponseOfComment: {
            code: string;
            message: string;
            data: null | components["schemas"]["Comment"];
            traceId: string;
        };
        /** @description Consistent HTTP response envelope. */
        ApiResponseOfContentView: {
            code: string;
            message: string;
            data: null | components["schemas"]["ContentView"];
            traceId: string;
        };
        /** @description Consistent HTTP response envelope. */
        ApiResponseOfIReadOnlyListOfContentView: {
            code: string;
            message: string;
            data: null | components["schemas"]["ContentView"][];
            traceId: string;
        };
        /** @description Consistent HTTP response envelope. */
        ApiResponseOfIReadOnlyListOfMenuView: {
            code: string;
            message: string;
            data: null | components["schemas"]["MenuView"][];
            traceId: string;
        };
        /** @description Consistent HTTP response envelope. */
        ApiResponseOfIReadOnlyListOfUserView: {
            code: string;
            message: string;
            data: null | components["schemas"]["UserView"][];
            traceId: string;
        };
        /** @description Consistent HTTP response envelope. */
        ApiResponseOfListOfTaxonomy: {
            code: string;
            message: string;
            data: null | components["schemas"]["Taxonomy"][];
            traceId: string;
        };
        /** @description Consistent HTTP response envelope. */
        ApiResponseOfMenuView: {
            code: string;
            message: string;
            data: null | components["schemas"]["MenuView"];
            traceId: string;
        };
        /** @description Consistent HTTP response envelope. */
        ApiResponseOfPageResultOfAssetView: {
            code: string;
            message: string;
            data: null | components["schemas"]["PageResultOfAssetView"];
            traceId: string;
        };
        /** @description Consistent HTTP response envelope. */
        ApiResponseOfPageResultOfAuditEntry: {
            code: string;
            message: string;
            data: null | components["schemas"]["PageResultOfAuditEntry"];
            traceId: string;
        };
        /** @description Consistent HTTP response envelope. */
        ApiResponseOfPageResultOfComment: {
            code: string;
            message: string;
            data: null | components["schemas"]["PageResultOfComment"];
            traceId: string;
        };
        /** @description Consistent HTTP response envelope. */
        ApiResponseOfPageResultOfContentView: {
            code: string;
            message: string;
            data: null | components["schemas"]["PageResultOfContentView"];
            traceId: string;
        };
        /** @description Consistent HTTP response envelope. */
        ApiResponseOfPageResultOfMenuTarget: {
            code: string;
            message: string;
            data: null | components["schemas"]["PageResultOfMenuTarget"];
            traceId: string;
        };
        /** @description Consistent HTTP response envelope. */
        ApiResponseOfSiteSettings: {
            code: string;
            message: string;
            data: null | components["schemas"]["SiteSettings"];
            traceId: string;
        };
        /** @description Consistent HTTP response envelope. */
        ApiResponseOfStatsView: {
            code: string;
            message: string;
            data: null | components["schemas"]["StatsView"];
            traceId: string;
        };
        /** @description Consistent HTTP response envelope. */
        ApiResponseOfTaxonomy: {
            code: string;
            message: string;
            data: null | components["schemas"]["Taxonomy"];
            traceId: string;
        };
        /** @description Consistent HTTP response envelope. */
        ApiResponseOfThemesView: {
            code: string;
            message: string;
            data: null | components["schemas"]["ThemesView"];
            traceId: string;
        };
        /** @description Consistent HTTP response envelope. */
        ApiResponseOfThemeView: {
            code: string;
            message: string;
            data: null | components["schemas"]["ThemeView"];
            traceId: string;
        };
        /** @description Consistent HTTP response envelope. */
        ApiResponseOfUserView: {
            code: string;
            message: string;
            data: null | components["schemas"]["UserView"];
            traceId: string;
        };
        /** @description Browser-visible file metadata. */
        AssetView: {
            id: string;
            name: string;
            contentType: string;
            /** Format: int64 */
            size: number;
            /** Format: date-time */
            createdAt: string;
            url: string;
        };
        /** @description Successful write audit; never stores passwords or content. */
        AuditEntry: {
            /** @description Actor identity. */
            actor?: string;
            /** @description Business action. */
            action?: string;
            /** @description Stable kind of the affected business object; blank on historical v1 entries. */
            targetType?: string;
            /** @description Identifier retained even after the target is deleted. */
            targetId?: string;
            /** @description Safe object name at the time of the operation; never credentials or body text. */
            targetName?: string;
            /** @description Opaque portable identifier. */
            id?: string;
            /**
             * Format: date-time
             * @description UTC creation timestamp.
             */
            createdAt?: string;
        };
        /** @description Single-use login challenge, image and validity period; never includes its answer. */
        CaptchaView: {
            id: string;
            image: string;
            /** Format: int32 */
            expiresInSeconds: number;
        };
        /** @description Moderated plain-text visitor comment. */
        Comment: {
            /** @description Parent article identifier. */
            contentId?: string;
            /** @description Visitor display name. */
            author?: string;
            /** @description Plain text only. */
            body?: string;
            /** @description Moderator approval. */
            approved?: boolean;
            /** @description Opaque portable identifier. */
            id?: string;
            /**
             * Format: date-time
             * @description UTC creation timestamp.
             */
            createdAt?: string;
        };
        /** @description Public comment input. */
        CommentInput: {
            contentId: string;
            author: string;
            body: string;
        };
        /** @description Editorial input with optimistic version. */
        ContentInput: {
            kind: string;
            slug: string;
            title: string;
            summary: string;
            html: string;
            coverId: string;
            categoryId: string;
            tagIds: string[];
            /** Format: int32 */
            version: number;
        };
        /** @description Immutable sanitized content snapshot. */
        ContentView: {
            id: string;
            kind: string;
            slug: string;
            title: string;
            summary: string;
            html: string;
            coverId: string;
            categoryId: string;
            tagIds: string[];
            /** Format: int32 */
            version: number;
            published: boolean;
            /** Format: date-time */
            publishedAt: null | string;
        };
        /** Format: binary */
        IFormFile: string;
        /** @description Login credentials. */
        LoginInput: {
            username: string;
            password: string;
            captchaId: string;
            captchaCode: string;
        };
        /** @description Menu input. */
        MenuInput: {
            label: string;
            url: string;
            /** Format: int32 */
            sort: number;
            /** @default  */
            parentId: string;
            /** @default custom */
            type: string;
            /** @default  */
            targetId: string;
            /** @default false */
            openInNewTab: boolean;
            /**
             * Format: int32
             * @default 0
             */
            version: number;
        };
        /** @description One selectable published content or archive destination. */
        MenuTarget: {
            id: string;
            label: string;
            url: string;
        };
        /** @description Resolved navigation destination; unavailable items are administrative only. */
        MenuView: {
            id: string;
            label: string;
            url: string;
            /** Format: int32 */
            sort: number;
            parentId: string;
            type: string;
            targetId: string;
            openInNewTab: boolean;
            /** Format: int32 */
            version: number;
            available: boolean;
        };
        /** @description Comment moderation input. */
        ModerateInput: {
            approved: boolean;
        };
        /** @description Server-side paginated result. */
        PageResultOfAssetView: {
            items: components["schemas"]["AssetView"][];
            /** Format: int64 */
            total: number;
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            pageSize: number;
        };
        /** @description Server-side paginated result. */
        PageResultOfAuditEntry: {
            items: components["schemas"]["AuditEntry"][];
            /** Format: int64 */
            total: number;
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            pageSize: number;
        };
        /** @description Server-side paginated result. */
        PageResultOfComment: {
            items: components["schemas"]["Comment"][];
            /** Format: int64 */
            total: number;
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            pageSize: number;
        };
        /** @description Server-side paginated result. */
        PageResultOfContentView: {
            items: components["schemas"]["ContentView"][];
            /** Format: int64 */
            total: number;
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            pageSize: number;
        };
        /** @description Server-side paginated result. */
        PageResultOfMenuTarget: {
            items: components["schemas"]["MenuTarget"][];
            /** Format: int64 */
            total: number;
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            pageSize: number;
        };
        /** @description Password rotation request. */
        PasswordInput: {
            currentPassword: string;
            newPassword: string;
        };
        /** @description Public site settings input. */
        SettingsInput: {
            title: string;
            description: string;
            logoId: string;
            keywords: string;
            /** @default  */
            subtitle: string;
            /** @default  */
            faviconId: string;
            /** @default zh-CN */
            language: string;
            /**
             * Format: int32
             * @default 12
             */
            homePageSize: number;
            /**
             * Format: int32
             * @default 12
             */
            categoryPageSize: number;
            /**
             * Format: int32
             * @default 12
             */
            tagPageSize: number;
            /**
             * Format: int32
             * @default 12
             */
            searchPageSize: number;
            /** @default false */
            blockSearchEngines: boolean;
            /** @default true */
            commentsEnabled: boolean;
            /** @default true */
            requireCommentApproval: boolean;
            /** @default false */
            commentsRequireLogin: boolean;
            /** @default  */
            footerText: string;
            /**
             * Format: int32
             * @default 0
             */
            version: number;
        };
        /** @description Site metadata stored in the selected database. */
        SiteSettings: {
            /** @description Website title. */
            title?: string;
            /** @description Website introduction. */
            description?: string;
            /** @description Logo asset identifier. */
            logoId?: string;
            /** @description SEO keywords. */
            keywords?: string;
            /** @description Short introduction displayed with the site identity. */
            subtitle?: string;
            /** @description Browser icon asset identifier. */
            faviconId?: string;
            /** @description Primary content language, not an interface translation setting. */
            language?: string;
            /**
             * Format: int32
             * @description Home page list size.
             */
            homePageSize?: number;
            /**
             * Format: int32
             * @description Category archive list size.
             */
            categoryPageSize?: number;
            /**
             * Format: int32
             * @description Tag archive list size.
             */
            tagPageSize?: number;
            /**
             * Format: int32
             * @description Search result list size.
             */
            searchPageSize?: number;
            /** @description Request search engines to exclude public pages from indexing. */
            blockSearchEngines?: boolean;
            /** @description Whether public comments can be read and submitted. */
            commentsEnabled?: boolean;
            /** @description Whether new comments await approval. */
            requireCommentApproval?: boolean;
            /** @description Require an existing enabled account for comment submission. */
            commentsRequireLogin?: boolean;
            /** @description Plain-text footer information. */
            footerText?: string;
            /**
             * Format: int32
             * @description Optimistic revision for all settings.
             */
            version?: number;
            /** @description Opaque portable identifier. */
            id?: string;
            /**
             * Format: date-time
             * @description UTC creation timestamp.
             */
            createdAt?: string;
        };
        /** @description Live overview counts. */
        StatsView: {
            /** Format: int64 */
            posts: number;
            /** Format: int64 */
            published: number;
            /** Format: int64 */
            pages: number;
            /** Format: int64 */
            pendingComments: number;
            /** Format: int64 */
            assets: number;
        };
        /** @description A category or tag. */
        Taxonomy: {
            /** @description category or tag. */
            kind?: string;
            /** @description Visible label. */
            name?: string;
            /** @description Archive URL segment. */
            slug?: string;
            /** @description Opaque portable identifier. */
            id?: string;
            /**
             * Format: date-time
             * @description UTC creation timestamp.
             */
            createdAt?: string;
        };
        /** @description Category/tag input. */
        TaxonomyInput: {
            kind: string;
            name: string;
            slug: string;
        };
        /** @description Atomically save this profile and activate it. */
        ThemeApplyInput: {
            themeId: string;
            options: components["schemas"]["ThemeOptions"];
            /** Format: int32 */
            version: number;
        };
        /** @description One packaged theme and its independent saved options. */
        ThemeDefinition: {
            id: string;
            name: string;
            description: string;
            thumbnail: string;
            defaultHeroTitle: string;
            defaults: components["schemas"]["ThemeOptions"];
            options: components["schemas"]["ThemeOptions"];
        };
        /** @description Editable, non-executable theme appearance. */
        ThemeOptions: {
            accentColor: string;
            heroTitle: string;
            heroDescription: string;
        };
        /** @description Administrative snapshot used for optimistic writes. */
        ThemesView: {
            activeThemeId: string;
            /** Format: int32 */
            version: number;
            themes: components["schemas"]["ThemeDefinition"][];
        };
        /** @description Public or authenticated-preview rendering configuration. */
        ThemeView: {
            themeId: string;
            options: components["schemas"]["ThemeOptions"];
        };
        /** @description Account administration input; password optional on edit. */
        UserInput: {
            username: string;
            displayName: string;
            role: string;
            enabled: boolean;
            password: null | string;
        };
        /** @description Account information safe for the browser. */
        UserView: {
            id: string;
            username: string;
            displayName: string;
            role: string;
            enabled: boolean;
        };
        /** @description Version required for publish, unpublish and delete. */
        VersionInput: {
            /** Format: int32 */
            version: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
