import { test, expect } from "@playwright/test";
import fs from "node:fs";
import { loginCaptcha } from "./login";

if (!process.env.CMS_TEST_BASE_URL || !process.env.CMS_TEST_CREDENTIALS_PATH) throw new Error("An isolated site is required.");
const credentials = JSON.parse(fs.readFileSync(process.env.CMS_TEST_CREDENTIALS_PATH, "utf8").replace(/^\uFEFF/, ""));

test("builder undo, rich text, mobile overrides and real site chrome remain isolated until publication", async ({ page }) => {
  test.setTimeout(120000);
  let csrf = (await (await page.request.get("/api/v1/auth/csrf")).json()).data.token;
  const login = await page.request.post("/api/v1/auth/login", { headers: { "X-CSRF-TOKEN": csrf }, data: { ...credentials, ...await loginCaptcha(page.request) } });
  expect(login.ok(), await login.text()).toBeTruthy();
  csrf = (await (await page.request.get("/api/v1/auth/csrf")).json()).data.token;
  async function call(path: string, method = "GET", data?: unknown) {
    const result = await page.request.fetch("/api/v1/" + path, { method, data, headers: { "X-CSRF-TOKEN": csrf } });
    expect(result.ok(), await result.text()).toBeTruthy(); return (await result.json()).data;
  }
  const settings = await call("admin/settings");
  await call("admin/settings", "PUT", { ...settings, title: "页面设计验收站", subtitle: "真实导航与页脚", footerText: "联系我们 · 测试页脚" });
  await call("admin/menu", "POST", { label: "服务介绍", url: "https://example.com/services", sort: 0 });
  const errors: string[] = [];
  page.on("pageerror", e => errors.push(e.message));
  page.on("dialog", dialog => void dialog.accept());
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.goto("/admin/pages/new");
  await page.getByLabel("标题", { exact: true }).fill("新页面设计");
  await page.getByRole("button", { name: "保存草稿", exact: true }).click();
  await expect(page).toHaveURL(/\/admin\/pages\/[a-f0-9]{32}$/);
  const id = page.url().split("/").pop()!;
  await page.getByRole("button", { name: "使用页面搭建", exact: true }).click();
  await page.locator(".block-inserter").getByRole("button", { name: "文字介绍", exact: true }).click();
  await page.getByLabel("模块标题", { exact: true }).fill("草稿模块");
  await page.getByLabel("模块说明", { exact: true }).fill("待排版文字");
  const frame = page.frameLocator('iframe[title="页面实时预览"]').first();
  await expect(frame.locator(".site-header")).toContainText("页面设计验收站");
  await expect(frame.getByRole("navigation", { name: "网站导航" })).toContainText("服务介绍");
  await expect(frame.locator(".site-footer")).toContainText("联系我们 · 测试页脚");
  const beforeUrl = page.url();
  await frame.getByRole("link", { name: "服务介绍", exact: true }).click();
  expect(page.url()).toBe(beforeUrl);
  await page.getByRole("button", { name: "使用富文本排版", exact: true }).click();
  const rich = page.locator(".builder-rich-editor .tiptap");
  await rich.fill("富文本说明");
  await rich.press("Control+A");
  await page.locator(".builder-rich-editor").getByRole("button", { name: "粗体", exact: true }).click();
  await expect(frame.locator(".page-block-rich strong")).toHaveText("富文本说明");
  await page.getByText("手机独立样式", { exact: true }).click();
  await page.getByLabel("手机文字对齐", { exact: true }).selectOption("center");
  await page.getByLabel("手机上下留白", { exact: true }).selectOption("large");
  await page.getByLabel("手机文字大小", { exact: true }).selectOption("large");
  await page.getByRole("button", { name: "手机", exact: true }).first().click();
  await expect.poll(() => frame.locator(".page-block").evaluate(el => getComputedStyle(el).textAlign)).toBe("center");
  expect(await frame.locator(".page-block").evaluate(el => getComputedStyle(el).paddingTop)).toBe("48px");
  expect(await frame.locator(".page-block-rich p").evaluate(el => getComputedStyle(el).fontSize)).toBe("20px");
  await page.getByLabel("仅在手机隐藏", { exact: true }).check();
  await expect(frame.locator(".page-block")).toBeHidden();
  await page.getByRole("button", { name: "桌面", exact: true }).first().click();
  await expect(frame.locator(".page-block")).toBeVisible();
  await page.getByLabel("仅在手机隐藏", { exact: true }).uncheck();
  await page.getByRole("button", { name: "保存并发布", exact: true }).click();
  await expect.poll(async () => (await call(`admin/contents/${id}`)).published).toBeTruthy();
  const original = await call(`admin/contents/${id}`);
  await page.getByRole("button", { name: "删除模块", exact: true }).click();
  await expect(page.locator(".block-outline-list li")).toHaveCount(0);
  await page.getByRole("button", { name: "撤销操作", exact: true }).click();
  await expect(page.locator(".block-outline-list li")).toHaveCount(1);
  await page.getByRole("button", { name: "重做操作", exact: true }).click();
  await expect(page.locator(".block-outline-list li")).toHaveCount(0);
  await page.getByRole("button", { name: "撤销操作", exact: true }).click();
  await page.getByLabel("模块标题", { exact: true }).fill("尚未公开的标题");
  await expect.poll(async () => (await call(`admin/contents/${id}`)).layout.blocks[0].title, { timeout: 15000 }).toBe("尚未公开的标题");
  await page.getByRole("button", { name: "撤销操作", exact: true }).click();
  await expect(page.getByLabel("模块标题", { exact: true })).toHaveValue("草稿模块");
  const publicContent = await call(`public/contents/${original.slug}`);
  expect(publicContent.layout.blocks[0].title).toBe("草稿模块");
  expect(publicContent.layout.blocks[0].html).toContain("<strong>富文本说明</strong>");
  await page.getByRole("button", { name: "手机", exact: true }).first().click();
  await page.screenshot({ path: `${process.env.CMS_TEST_ARTIFACTS}/builder-enhancements.png`, fullPage: true });
  expect(errors).toEqual([]);
});
