import { test, expect } from "@playwright/test";
import fs from "node:fs";
import { createHmac } from "node:crypto";
import { loginCaptcha } from "./login";

test("digital sales, channel settings, private receipts and signed test callbacks", async ({ page, browser }) => {
  test.setTimeout(180000);
  if (!process.env.CMS_TEST_CREDENTIALS_PATH || !process.env.CMS_TEST_ARTIFACTS) throw new Error("Disposable site required");
  const credentials = JSON.parse(fs.readFileSync(process.env.CMS_TEST_CREDENTIALS_PATH, "utf8"));
  let csrf = (await (await page.request.get("/api/v1/auth/csrf")).json()).data.token;
  const login = await page.request.post("/api/v1/auth/login", { headers: { "X-CSRF-TOKEN": csrf }, data: { ...credentials, ...await loginCaptcha(page.request) } });
  expect(login.ok(), await login.text()).toBeTruthy();
  csrf = (await (await page.request.get("/api/v1/auth/csrf")).json()).data.token;
  async function call(path: string, method = "GET", data?: unknown) {
    const response = await page.request.fetch("/api/v1/" + path, { method, data, headers: { "X-CSRF-TOKEN": csrf } });
    expect(response.ok(), await response.text()).toBeTruthy(); return (await response.json()).data;
  }
  const product = await call("admin/contents", "POST", { kind: "product", slug: "commerce-browser", title: "数字资料验收", summary: "购买后下载资料", html: "<p>资料说明</p>", coverId: "", categoryId: "", tagIds: [], version: 0 });
  await call(`admin/contents/${product.id}/publish`, "POST", { version: product.version });
  await page.goto(`/admin/commerce-products/${product.id}`);
  await page.getByLabel("售价", { exact: true }).fill("12.50");
  await page.getByLabel("付费交付文件").setInputFiles({ name: "paid-guide.txt", mimeType: "text/plain", buffer: Buffer.from("paid private guide") });
  await expect(page.getByText(/当前交付：paid-guide.txt/)).toBeVisible();
  await page.getByLabel("上架销售").check();
  await page.getByRole("button", { name: "保存销售设置" }).click();
  await expect(page.getByRole("status")).toContainText("商品销售设置已保存");
  const sale = await call(`admin/commerce/products/${product.id}`);
  expect(sale.price).toBe(1250);
  expect((await call("admin/assets")).items.some((a: { id: string }) => a.id === sale.fileId)).toBeFalsy();
  const guest = await browser.newContext({ baseURL: process.env.CMS_TEST_BASE_URL, ignoreHTTPSErrors: process.env.CMS_TEST_SELF_SIGNED === "1" });
  const visitor = await guest.newPage();
  await visitor.goto("/products/commerce-browser");
  await expect(visitor.getByText("暂未开放在线收款，请联系商家咨询。")).toBeVisible();
  expect((await guest.request.get("/api/v1/admin/commerce/settings")).status()).toBe(401);
  expect((await guest.request.post("/api/v1/shop/orders", { data: {} })).status()).toBe(400);
  await page.goto("/admin/payments");
  await expect(page.getByLabel("启用支付宝", { exact: true })).toBeVisible();
  await expect(page.getByLabel("启用微信支付", { exact: true })).toBeVisible();
  await page.getByLabel("网站 HTTPS 地址", { exact: true }).fill("https://shop.example.com");
  const stripe = page.locator("section.panel").filter({ has: page.getByRole("heading", { name: /^Stripe / }) });
  await stripe.getByLabel("启用Stripe", { exact: true }).check();
  await stripe.getByLabel("测试环境（不开放正式文件下载）", { exact: true }).check();
  await page.getByRole("button", { name: "保存支付设置" }).click();
  await expect(page.locator('.alert[role="alert"]')).toContainText("Stripe 需要账户 ID");
  await stripe.getByLabel("Stripe 账户 ID（acct_ 开头）", { exact: true }).fill("acct_browser");
  await stripe.getByLabel("Secret Key", { exact: true }).fill("sk_test_browser_not_a_real_key");
  await stripe.getByLabel("Webhook 签名密钥", { exact: true }).fill("whsec_browser_not_a_real_key");
  await page.getByRole("button", { name: "保存支付设置" }).click();
  await expect(page.getByRole("status")).toContainText("支付设置已保存");
  await expect(stripe.getByLabel("Secret Key", { exact: true })).toHaveValue("");
  expect(JSON.stringify(await call("admin/commerce/settings"))).not.toContain("whsec_browser");
  await page.setViewportSize({ width: 1280, height: 900 });
  await page.screenshot({ path: `${process.env.CMS_TEST_ARTIFACTS}/commerce-settings.png`, fullPage: true });
  await visitor.setViewportSize({ width: 390, height: 844 });
  await visitor.reload();
  await expect(visitor.getByRole("radio", { name: "Stripe（测试，不开放下载）" })).toBeVisible();
  await visitor.getByLabel("联系邮箱", { exact: true }).fill("buyer@example.com");
  await visitor.getByRole("button", { name: "立即购买", exact: true }).click();
  await expect(visitor).toHaveURL(/\/orders\/[a-f0-9]{32}$/);
  await expect(visitor.getByRole("status")).toContainText("待付款");
  const id = visitor.url().split("/").pop()!;
  const receipt = await visitor.evaluate(id => localStorage.getItem("cms.order." + id), id);
  expect(receipt).toMatch(/^[a-f0-9]{64}$/);
  expect((await guest.request.get(`/api/v1/shop/orders/${id}`)).status()).toBe(404);
  expect((await guest.request.get(`/api/v1/shop/orders/${id}/download`, { headers: { "X-Order-Token": receipt! } })).status()).toBe(403);
  const forged = await guest.request.post("/api/v1/payments/stripe/notify", { data: "{}", headers: { "Stripe-Signature": "t=0,v1=bad", "Content-Type": "application/json" } });
  expect(forged.status()).toBe(400);
  expect((await forged.json()).code).toBe("INVALID_PAYMENT_SIGNATURE");
  const body = JSON.stringify({ type: "checkout.session.completed", data: { object: { id: "cs_browser_" + id, client_reference_id: id, amount_total: 1250, currency: "cny", payment_intent: "pi_browser_" + id, payment_status: "paid", livemode: false } } });
  const timestamp = Math.floor(Date.now() / 1000);
  const signature = createHmac("sha256", "whsec_browser_not_a_real_key").update(timestamp + "." + body).digest("hex");
  for (let replay = 0; replay < 2; replay++) {
    const response = await guest.request.post("/api/v1/payments/stripe/notify", { data: body, headers: { "Stripe-Signature": `t=${timestamp},v1=${signature}`, "Content-Type": "application/json" } });
    expect(response.ok(), await response.text()).toBeTruthy();
  }
  await expect(visitor.getByRole("status")).toContainText("已付款", { timeout: 10000 });
  await expect(visitor.getByRole("button", { name: "下载商品文件" })).toHaveCount(0);
  expect((await guest.request.get(`/api/v1/shop/orders/${id}/download`, { headers: { "X-Order-Token": receipt! } })).status()).toBe(403);
  expect(await visitor.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy();
  await visitor.screenshot({ path: `${process.env.CMS_TEST_ARTIFACTS}/commerce-order-mobile.png`, fullPage: true });
  await visitor.evaluate(() => localStorage.clear());
  await visitor.reload();
  await visitor.getByLabel("订单凭证", { exact: true }).fill(receipt!);
  await visitor.getByRole("button", { name: "查询订单", exact: true }).click();
  await expect(visitor.getByRole("status")).toContainText("已付款");
  await page.goto("/admin/commerce-orders");
  await page.getByRole("button", { name: "查看订单", exact: true }).click();
  await expect(page.getByRole("dialog")).toContainText("测试订单不开放正式下载");
  await guest.close();
});
