import { test, expect } from "@playwright/test";
import fs from "node:fs";
import { loginCaptcha } from "./login";

if (!process.env.CMS_TEST_BASE_URL || !process.env.CMS_TEST_CREDENTIALS_PATH) throw new Error("An isolated site is required.");
const credentials = JSON.parse(fs.readFileSync(process.env.CMS_TEST_CREDENTIALS_PATH, "utf8").replace(/^\uFEFF/, ""));

test("build, publish, reuse and restore page layouts with responsive public rendering", async ({ browser }) => {
  test.setTimeout(180000);
  const context = await browser.newContext({ baseURL: process.env.CMS_TEST_BASE_URL });
  let csrf = (await (await context.request.get("/api/v1/auth/csrf")).json()).data.token;
  const login = await context.request.post("/api/v1/auth/login", { headers: { "X-CSRF-TOKEN": csrf }, data: { ...credentials, ...await loginCaptcha(context.request) } });
  expect(login.ok(), await login.text()).toBeTruthy();
  csrf = (await (await context.request.get("/api/v1/auth/csrf")).json()).data.token;
  async function call(path: string, method = "GET", data?: unknown) {
    const response = await context.request.fetch("/api/v1/" + path, { method, data, headers: { "X-CSRF-TOKEN": csrf } });
    expect(response.ok(), await response.text()).toBeTruthy(); return (await response.json()).data;
  }
  let article = await call("admin/contents", "POST", { kind: "post", slug: "builder-dynamic-post", title: "动态文章验收", summary: "真实发布内容自动进入模块", html: "<p>内容正文</p>", coverId: "", categoryId: "", tagIds: [], version: 0 });
  await call(`admin/contents/${article.id}/publish`, "POST", { version: article.version });
  const page = await context.newPage(), errors: string[] = [];
  page.on("pageerror", e => errors.push(e.message));
  page.on("dialog", dialog => void dialog.accept());
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.goto("/admin/templates/new");
  await page.getByLabel("标题", { exact: true }).fill("企业首页模板验收");
  await page.getByRole("button", { name: "保存草稿", exact: true }).click();
  await expect(page).toHaveURL(/\/admin\/templates\/[a-f0-9]{32}$/);
  await page.getByText("模板、公共区块与页面设置", { exact: true }).click();
  await page.getByText("选择起始模板或已发布模板", { exact: true }).click();
  await page.getByRole("button", { name: "企业首页", exact: true }).click();
  await page.getByLabel("模块标题", { exact: true }).fill("让产品价值被看见");
  await page.getByLabel("模块说明", { exact: true }).fill("自由组合内容模块，呈现品牌、产品与客户案例。");
  await page.getByText("外观与手机样式", { exact: true }).click();
  await page.getByRole("combobox", { name: "背景风格", exact: true }).selectOption("accent");
  await page.getByRole("button", { name: "常见问题", exact: true }).click();
  await page.getByLabel("项目标题", { exact: true }).fill("页面发布后可以继续修改吗？");
  await page.getByLabel("项目说明", { exact: true }).fill("可以，草稿不会影响网站，发布后才更新。");
  await page.getByRole("button", { name: "上移", exact: true }).click();
  await page.locator(".block-inserter").getByRole("button", { name: "文字介绍", exact: true }).click();
  await page.getByLabel("模块标题", { exact: true }).fill("我们的服务");
  await page.getByLabel("模块说明", { exact: true }).fill("从内容发布到客户咨询，保持清晰一致的访问体验。");
  await page.locator(".block-inserter").getByRole("button", { name: "图片展示", exact: true }).click();
  await page.getByLabel("上传模块图片", { exact: true }).setInputFiles({ name: "builder.png", mimeType: "image/png", buffer: Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+a0foAAAAASUVORK5CYII=", "base64") });
  await expect(page.locator(".builder-image-fields > img")).toBeVisible();
  await page.getByLabel("图片说明", { exact: true }).fill("模板附件验收图片");
  await page.locator(".block-inserter").getByRole("button", { name: "行动按钮", exact: true }).click();
  await page.getByLabel("按钮文字", { exact: true }).fill("查看文章");
  await page.getByLabel("按钮链接", { exact: true }).fill("/search");
  await page.getByRole("button", { name: "保存草稿", exact: true }).click();
  await expect(page).toHaveURL(/\/admin\/templates\/[a-f0-9]{32}$/);
  const templateId = page.url().split("/").pop()!;
  await page.getByRole("button", { name: "发布模板", exact: true }).click();
  await expect.poll(async () => (await call(`admin/contents/${templateId}`)).published).toBeTruthy();
  const template = await call(`admin/contents/${templateId}`);
  expect(template.layout.blocks.map((x: { type: string }) => x.type)).toEqual(["hero", "cards", "posts", "faq", "contact", "text", "image", "cta"]);
  await page.getByText("整页预览（含页头、页脚与动态内容）", { exact: true }).click();
  const frame = page.frameLocator('iframe[title="页面实时预览"]').first();
  await expect(frame.getByRole("heading", { name: "让产品价值被看见" })).toBeVisible();
  await expect(frame.getByRole("link", { name: "动态文章验收" })).toBeVisible();
  await page.locator(".layout-preview").getByRole("button", { name: "手机", exact: true }).click();
  await expect.poll(async () => await frame.locator("body").evaluate(() => innerWidth)).toBe(375);
  expect(await frame.locator(".page-card-grid").first().evaluate(el => getComputedStyle(el).gridTemplateColumns.split(" ").length)).toBe(1);
  await page.screenshot({ path: `${process.env.CMS_TEST_ARTIFACTS}/builder-desktop.png`, fullPage: true });
  await page.goto("/admin/pages/new");
  await page.getByLabel("标题", { exact: true }).fill("品牌首页验收");
  await page.getByRole("button", { name: "保存草稿", exact: true }).click();
  await expect(page).toHaveURL(/\/admin\/pages\/[a-f0-9]{32}$/);
  await page.getByRole("button", { name: "使用页面搭建", exact: true }).click();
  await page.getByText("模板、公共区块与页面设置", { exact: true }).click();
  await page.getByText("选择起始模板或已发布模板", { exact: true }).click();
  await page.getByRole("button", { name: "企业首页模板验收", exact: true }).click();
  await page.getByRole("button", { name: "保存并发布", exact: true }).click();
  await expect(page).toHaveURL(/\/admin\/pages\/[a-f0-9]{32}$/);
  await expect(page.getByText("已发布，网站内容已更新。", { exact: true })).toBeVisible();
  const pageId = page.url().split("/").pop()!;
  const originalPage = await call(`admin/contents/${pageId}`);
  await page.goto("/admin/settings");
  await page.getByLabel("网站首页", { exact: true }).selectOption(pageId);
  await page.getByRole("button", { name: "保存设置", exact: true }).click();
  await expect(page.getByText("站点设置已更新。", { exact: true })).toBeVisible();
  const guest = await browser.newContext({ baseURL: process.env.CMS_TEST_BASE_URL });
  const publicPage = await guest.newPage();
  publicPage.on("pageerror", e => errors.push(e.message));
  const response = await publicPage.goto("/");
  expect(await response!.text()).toContain("让产品价值被看见");
  await expect(publicPage.getByRole("heading", { name: "让产品价值被看见" })).toBeVisible();
  await expect(publicPage.locator('[data-inquiry-slot] .inquiry-section')).toHaveCount(1);
  await publicPage.getByText("页面发布后可以继续修改吗？", { exact: true }).click();
  await expect(publicPage.getByText("可以，草稿不会影响网站，发布后才更新。", { exact: true })).toBeVisible();
  await publicPage.getByRole("button", { name: "咨询 / 预约演示", exact: true }).click();
  await publicPage.getByLabel("称呼", { exact: true }).fill("搭建页面访客");
  await publicPage.getByLabel("联系方式", { exact: true }).fill("builder@example.test");
  await publicPage.getByLabel("需求描述", { exact: true }).fill("了解页面搭建服务");
  await publicPage.locator('input[name="consent"]').check();
  await publicPage.getByRole("button", { name: "提交咨询", exact: true }).click();
  await expect(publicPage.getByText("咨询已提交，我们会通过你留下的联系方式回复。", { exact: true })).toBeVisible();
  const themes = await call("admin/themes");
  let themeVersion = themes.version;
  for (const theme of themes.themes) {
    themeVersion = (await call("admin/themes/active", "PUT", { themeId: theme.id, options: theme.options, version: themeVersion })).version;
    for (const width of [1440, 768, 375]) {
      await publicPage.setViewportSize({ width, height: 1000 });
      await publicPage.goto("/");
      await expect(publicPage.getByRole("heading", { name: "让产品价值被看见" })).toBeVisible();
      expect(await publicPage.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1), `${theme.id} ${width}`).toBeTruthy();
      if (width === 1440) {
        const button = publicPage.getByRole("link", { name: "查看文章", exact: true });
        await button.hover();
        const ratio = await button.evaluate(el => {
          const style = getComputedStyle(el);
          const luminance = (color: string) => color.match(/[\d.]+/g)!.slice(0, 3).map(Number).map(v => v / 255).map(v => v <= .04045 ? v / 12.92 : ((v + .055) / 1.055) ** 2.4).reduce((sum, v, i) => sum + v * [.2126, .7152, .0722][i], 0);
          const a = luminance(style.color), b = luminance(style.backgroundColor);
          return (Math.max(a, b) + .05) / (Math.min(a, b) + .05);
        });
        expect(ratio, `${theme.id} hovered CTA contrast`).toBeGreaterThanOrEqual(4.5);
      }
      if (["classic", "retypeset", "clarity"].includes(theme.id)) await publicPage.screenshot({ path: `${process.env.CMS_TEST_ARTIFACTS}/builder-public-${theme.id}-${width}.png`, fullPage: true });
    }
  }
  await page.goto(`/admin/pages/${pageId}`);
  await page.frameLocator('iframe[title="拖拽设计画布"]').getByRole("heading", { name: "让产品价值被看见" }).click();
  await page.route(`**/api/v1/admin/contents/${pageId}`, route => route.request().method() === "PUT" ? route.fulfill({ status: 500, contentType: "application/json", body: JSON.stringify({ code: "TEST_FAILURE", message: "模拟布局保存失败" }) }) : route.continue());
  await page.getByLabel("模块标题", { exact: true }).fill("尚未发布的改动");
  await page.getByRole("button", { name: "保存草稿", exact: true }).click();
  await expect(page.getByText("模拟布局保存失败", { exact: false }).first()).toBeVisible();
  await page.reload();
  await expect(page.getByRole("heading", { name: "发现未提交的本机恢复副本" })).toBeVisible();
  await page.unroute(`**/api/v1/admin/contents/${pageId}`);
  await page.getByRole("button", { name: "恢复输入", exact: true }).click();
  await expect(page.getByLabel("模块标题", { exact: true })).toHaveValue("尚未发布的改动");
  await page.getByRole("button", { name: "保存草稿", exact: true }).click();
  await expect.poll(async () => (await call(`admin/contents/${pageId}`)).layout.blocks[0].title).toBe("尚未发布的改动");
  expect((await call("public/home")).layout.blocks[0].title).toBe("让产品价值被看见");
  const revision = page.locator(".history-list li").filter({ hasText: `版本 ${originalPage.version} ·` });
  await revision.getByRole("button", { name: "恢复为草稿" }).click();
  await expect.poll(async () => (await call(`admin/contents/${pageId}`)).layout.blocks[0].title).toBe("让产品价值被看见");
  await page.setViewportSize({ width: 375, height: 1000 });
  await expect.poll(async () => { const box = await page.locator("#admin-navigation").boundingBox(); return box!.x + box!.width; }).toBeLessThanOrEqual(1);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBeTruthy();
  await page.screenshot({ path: `${process.env.CMS_TEST_ARTIFACTS}/builder-mobile.png`, fullPage: true, animations: "disabled" });
  expect(errors).toEqual([]);
  await guest.close(); await context.close();
});
